% All pre-amble stuff should go into ../include/MainDocument.Rnw
\title{Start Teaching with R}
\author{Randall Pruim and Nicholas Horton and Daniel Kaplan}
\date{DRAFT: \today}
\Sexpr{set_parent('../../include/MainDocument.Rnw')} % All the latex pre-amble for the book

\maketitle

\tableofcontents

\newpage

This is the start of the book project.

\chapter{The first chapter}

\import{../}{example-file}


\chapter{The second chapter}

\import{../}{example-file}