

\documentclass[open-any,12pt]{tufte-book}

\usepackage{../include/RBook}
\def\tilde{\texttt{\~}}

\title{R Commands for Teaching Statistics}
\author{Nicholas J. Horton,\\Daniel Kaplan and\\Randall Pruim}
\date{DRAFT: \today}

\renewenvironment{knitrout}{\relax}{\noindent}
\begin{document}


\maketitle

\tableofcontents

\newpage

<<include=FALSE>>=
..makingMaster.. <- TRUE
@

<<child='../Starting/FrontMatter.Rnw', eval=TRUE>>=
@

<<child='Core.Rnw', eval=TRUE>>=
@


\end{document}
