

\documentclass[open-any,12pt]{tufte-book}

\usepackage{../include/RBook}
\def\tilde{\texttt{\~}}

\title{Compendium of R Commands for Teaching Stats}
\author{Nicholas J. Horton\\ Daniel Kaplan\\Randall Pruim}
\date{DRAFT: \today}

\renewenvironment{knitrout}{\relax}{\noindent}
\begin{document}


\maketitle

\tableofcontents

\newpage

<<include=FALSE>>=
..makingMaster.. <- TRUE
@

<<child='Core.Rnw', eval=TRUE>>=
@


\end{document}
